### ISSUE TITLE
Step10の7　kubernetes APIライブラリの利用でサンプルが上手く動作しないです。

### ISSUE THREAD

**Issue by OogakiAkiya** [takara9/vagrant-kubernetes#4]
P262のpythonのコードが上手く動作しなかったため、一度ご確認いただきたいです。

おこなった内容はminikube上で
```
$kubectl apply -f taskQueue-deploy
$docker build --tag job-init:0.1 ./job-initiator.py
$docker run -it --rm --name kube -v `pwd`/py:/py -v ~/.kube:/root/.kube -v ~/.minikube:/Users/[user名]/.minikube job-init:0.1 bash
```

コンテナを起動した後
```
root@ddbfd700e12c:/# cd py

root@ddbfd700e12c:/py# python job-initiator.py
Traceback (most recent call last):
  File "job-initiator.py", line 64, in <module>
    queue = create_queue()
  File "job-initiator.py", line 21, in create_queue
    conn = pika.BlockingConnection(qmgr_pram)
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 359, in __init__
    self._impl = self._create_connection(parameters, _impl_class)
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
```
以上の内容のエラーが出ております。

**Comment by takara9** [comment]
Issueを登録いただき、ありがとうございます。こちらでも確認してみます。こちらで指定しておいて、申し訳ないのですが、問題のコードの存在する https://github.com/takara9/codes_for_lessons のIssueへ書き込み場所を変えて頂いても良いでしょうか？　申し訳ありません。
